channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - snakemake>=8
  - python>=3.8
  - pip
  - biopython
  - seqkit 
  - wget 
  - sra-tools
  - blast=2.10
  - gcc
  - pip:
    - snakemake-executor-plugin-cluster-generic
    - matplotlib>3.3.2
    - pandas
    - tmhmm.py
    - numpy==1.23.2